name = "client"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
lustre = ">= 5.0.0 and < 6.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 1.0.0 and < 2.0.0"
